//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Banking
{
    using System;
    using System.Collections.Generic;
    
    public partial class Account
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Account()
        {
            this.TransactionLogs = new HashSet<TransactionLog>();
        }
    
        public int Accountno { get; set; }
        public Nullable<short> CustomerID { get; set; }
        public int CurrentBalance { get; set; }
        public byte AccountTypeID { get; set; }
        public byte AccountStatusTypeID { get; set; }
        public short BranchID { get; set; }
    
        public virtual AccountType AccountType { get; set; }
        public virtual AccountStatusType AccountStatusType { get; set; }
        public virtual Branch Branch { get; set; }
        public virtual Customer Customer { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<TransactionLog> TransactionLogs { get; set; }
    }
}
