//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Banking
{
    using System;
    using System.Collections.Generic;
    
    public partial class FailedTransactionLog
    {
        public int FailedTransactionID { get; set; }
        public byte FailedTransactionErrorTypeID { get; set; }
        public System.DateTime FailedTransactionErrorTime { get; set; }
    
        public virtual FailedTransactionErrorType FailedTransactionErrorType { get; set; }
    }
}
