//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Banking
{
    using System;
    using System.Collections.Generic;
    
    public partial class TransactionLog
    {
        public int TransactionID { get; set; }
        public System.DateTime TransactionDate { get; set; }
        public byte TransactionTypeID { get; set; }
        public decimal TransactionAmount { get; set; }
        public decimal PreviousBalance { get; set; }
        public int Accountno { get; set; }
        public byte BeneficiaryID { get; set; }
        public short CustomerID { get; set; }
    
        public virtual Account Account { get; set; }
        public virtual Beneficiary Beneficiary { get; set; }
        public virtual Customer Customer { get; set; }
        public virtual TransactionType TransactionType { get; set; }
    }
}
