//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Banking.Models
{
    using System;
    using System.Collections.Generic;
    using System.ComponentModel.DataAnnotations;

    public partial class Customer
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Customer()
        {
            this.Accounts = new HashSet<Account>();
            this.TransactionLogs = new HashSet<TransactionLog>();
            this.UserAddresses = new HashSet<UserAddress>();
        }
    
        public short CustomerID { get; set; }
        [Display(Name = "FirstName")]
        public string CustomerFirstName { get; set; }
        [Display(Name = "LastName")]
        public string CustomerLastName { get; set; }
        [DataType(DataType.Date)]
        [Display(Name = "DOB")]
        public System.DateTime CustomerDateOfBirth { get; set; }
        [DataType(DataType.EmailAddress)]
        [Display(Name = "Email Id")]
        public string EmailAddress { get; set; }
        [DataType(DataType.PhoneNumber)]
        [Display(Name = "Mobile Number")]
        public string CellPhone { get; set; }
        [Display(Name = "Adhaar Number")]
        public string AadhaarNumber { get; set; }
        public short UserID { get; set; }
        [Display(Name = "Occupation Type")]
        public string OccupationType { get; set; }
        
        public string OccupationSource { get; set; }
        [Display(Name = "Income")]
        public Nullable<decimal> OccupationIncome { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Account> Accounts { get; set; }
        public virtual User User { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<TransactionLog> TransactionLogs { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<UserAddress> UserAddresses { get; set; }
    }
}
