//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Banking.Models
{
    using System;
    using System.Collections.Generic;
    using System.ComponentModel.DataAnnotations;
    using System.ComponentModel.DataAnnotations.Schema;
    using System.Web.Mvc;

    public partial class User
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public User()
        {
            this.Customers = new HashSet<Customer>();
        }
        [Key]
        public short UserID { get; set; }
        [RemoteAttribute("IsUserExist", "Register", ErrorMessage = "Email Id Does not exist")]
        [Required]
        [Display(Name = "User Name")]
        public string UserName { get; set; }
        [Required]
        [DataType(DataType.Password)]
        [Display(Name = "Password")]
        public string UserPassword { get; set; }
        [Required]
        [Display(Name = "Confirm Password")]
        [NotMapped]
        [DataType(DataType.Password)]
        [System.ComponentModel.DataAnnotations.Compare("UserPassword", ErrorMessage = "Passwords do not match")]
        public string ConfirmPassword {get; set;}
        [Display(Name = "Transaction Password")]
        [Required]
        public string UserTransactionPassword { get; set; }
        public Nullable<short> RoleID { get; set; }
        public string UserPictureURL { get; set; }
        public string Photo_Name { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Customer> Customers { get; set; }
        public virtual Role Role { get; set; }
    }
}
